### ISSUE TITLE
Agregar botón de información

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#18]
## NO IMPLEMENTAR AUN

![image](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/111393321/7e90027d-51c0-43b4-8484-ac6e67f89f5a)

La idea es implementar un código QR que podés escanear  durante el evento y que te lleve a este [Canvas ](https://www.canva.com/design/DAFnuAJKd-c/2dZlVfpmrwOug-GOSVianA/view?utm_content=DAFnuAJKd-c&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink) explicativo.

Debajo del QR dejar un label con el siguiente texto: "¡Sumá tu juego!"

**Comment by Streq** [comment]
Che y reemplazar el boton directamente por un QR a la wiki no va?

**Comment by PlayJamDevs** [comment]
> Che y reemplazar el boton directamente por un QR a la wiki no va?

Si. Está más piola. Pero no sería a la Wiki seguramente. Pero tu idea me gusta mas y es más sencilla. Te chiflo nuevamente.

**Comment by PlayJamDevs** [comment]
@Streq ya se puede implementaR!
