### ISSUE TITLE
Cambios sugeridos

### ISSUE THREAD

**Issue by jh62** [PlayJamDevs/Play-Jam-Launcher-2#2]
https://github.com/PlayJamDevs/Play-Jam-Launcher-2/blob/a494006627d829691f7d5a46114972c2c177a9dc/scenes/GameSelection/GameSelection.gd#LL96C1-L96C1

# 1
`if !has_executable and current_file.begins_with("Ejecutable") and _is_executable(full_path):`

La linea `current_file.begins_with("Ejecutable")` podés eliminarla

# 2
`current_file == "Cover.png"` cambiar por `current_file.nocasecmp_to("cover.png")`

usar `nocasecmp_to` siempre que sea posible o sea sensato hacerlo para prevenir errores.

# 3

La búsqueda de juego debe fallar si no tiene ejecutable, en cualquier otro caso cargarlo igual y dejar la info en blanco y poner una imagen genérica (podemos llamarla "unknown_error.png") para indicar que no existe el cover del juego.

```
        if !has_executable:
		push_error("couldn't load game for folder " + game_dir_path + ", executable is missing.")
		return null
		
	if !has_info or !has_cover:
		var missing = []
		if !has_info:
			missing.append("info.json")
		if !has_cover:
			missing.append("cover.png")
		var suffix = missing[0]
		for i in range(1, missing.size()-1):
			suffix += ", "
			suffix += missing[i]
		suffix += " and " + missing[-1]
		
		push_warning("couldn't load all game data for folder " + game_dir_path + ", missing " + suffix + ".")```

**Comment by PlayJamDevs** [comment]
@Streq Estos cambios los actualicé en la wiki también. Estaba mal explicado.

**Comment by PlayJamDevs** [comment]
@Streq Esto lo podemos cerrar?

**Comment by Streq** [comment]
si
