### ISSUE TITLE
Agregar timeout y posibilidad de abortar

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#21]
![Godot_v3 5 1-stable_win64_HoazDFDFcc](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/111393321/d37a32fd-f4ac-4004-a223-1f196376fe92)

Agregar:

- Timeout: cuando se pide ejecutar un juego agregar un timeout que cuente de 3 a 0. El timeout no tiene que durar necesariamente 3 segundos, puede ser una animacion fija y le ajustamos el playback.
- Agregar instruccion de como abortar el lanzamiento.
- Cuando se lanza un juego, hacer un fade to black de 1 segundo y que ejecute el juego.

**Comment by PlayJamDevs** [comment]
Incluso el fade puede empezar con el mismo countdown desde 0.0 hasta 0.5 y cuando termina el countdown, acelerar el fade hasta opacidad 1.0. De esa manera se va tambien generando un contraste con el fondo y es mas evidente q se te acaba el tiempo para cancelar.

**Comment by Streq** [comment]
Uso una fuente en especifico?
