### ISSUE TITLE
Filtrar nombres de archivos reservados

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#29]
No leer archivos por defecto de otros programas que puedan confundirse con el ejecutable principal.

Crear una lista de excepciones de nombres reservados, la cual debería ser consultada por el launcher antes de aceptar un ejecutable como tal.

Criterios:

1. Primero verificar si existen > 1 .exe
2. Filtrar entradas invalidas: UnityCrashHandler32.exe, UnityCrashHandler64.exe, etc...

Los juegos van a ser pre-aprobados, así que no debería haber excepciones más alla de estas con nombres y archivos particulares.

**Comment by Streq** [comment]
Se podria agregar opcionalmente el nombre del ejecutable al json como ultimo recurso para desambiguar en casos border donde haya mas ejecutables no contemplados
