### ISSUE TITLE
Implementar vista del menú según wiki.

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#3]
[Ver](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/wiki/03---Submenu-de-juegos)

**Comment by Streq** [comment]
Hay proporciones exactas que respetar? se asume pantalla 1920x1080 como está configurado en el proyecto? ahora mismo el tamaño de textura de cover se asume como 1200x350, y si se pasa de eso o se queda corto se centra y/o croppea

**Comment by Streq** [comment]
![Image](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/8540266/2b087df5-bf30-4f0f-a08d-6093d64ccec2)

screenshot de cómo se ve ahora

**Comment by PlayJamDevs** [comment]
> Hay proporciones exactas que respetar? se asume pantalla 1920x1080 como está configurado en el proyecto? ahora mismo el tamaño de textura de cover se asume como 1200x350, y si se pasa de eso o se queda corto se centra y/o croppea

Se ve joya. Asumamos resolución 1920x1080 y se puede poner que expanda.
