### ISSUE TITLE
Arreglar overlap entre elementos del UI de selección de categoría

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#32]
![image](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/111393321/a338561b-2520-42d9-a07c-dfb4b1600c45)

@Streq Hay un overlap entre los recuadros de categoría y el banner violeta con la descripción. Dejarle un mínimo de 4px o algo que quede bien.

**Comment by Streq** [comment]
![image](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/8540266/08d3d908-3412-4752-bc9b-ab2b3ed83e92)
en mi monitor de 1920x1080, en todo caso si persiste se deja para el final

**Comment by PlayJamDevs** [comment]
Confirmo 👍 Si abro el launcher en monitor 2 no tiene gap, pero si paso la ventana a el de 1920x1080 y vuelvo al menu principal, el gap esta bien. En la tele se deberia ver bien.
