### ISSUE TITLE
Agregar setting en JSON

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#37]
Agregar un setting en JSON que tome un INT e integrarlo al launcher con estos valores de referencia:

1. Joystick
2. Mouse
3. Teclado
4. Mouse y teclado

**Comment by Streq** [comment]
Es necesario que sea un int? Por ahi podria ser algo mas laxo y dentro del launcher mappearlo a int. Por ej para 
- 1: chequear si contiene "joystick"
- 2: chequear si contiene "mouse" pero no teclado ni keyboard
- 3: chequear si contiene "teclado" o "keyboard" pero no "mouse"
- 4: chequear si contiene "teclado"/"keyboard" "mouse"
- y alternativamente si el valor es un numero entre 1 y 4 mappear ese numero directamentr

**Comment by PlayJamDevs** [comment]
> Es necesario que sea un int? Por ahi podria ser algo mas laxo y dentro del launcher mappearlo a int. Por ej para
> 
> * 1: chequear si contiene "joystick"
> * 2: chequear si contiene "mouse" pero no teclado ni keyboard
> * 3: chequear si contiene "teclado" o "keyboard" pero no "mouse"
> * 4: chequear si contiene "teclado"/"keyboard" "mouse"
> * y alternativamente si el valor es un numero entre 1 y 4 mappear ese numero directamentr

Manejalo como creas mejor. Lo importante es el funcionamiento realmente. La idea es dejar joystick, mouse y teclado y que cada jugador use el mando que sea apropiado para ese juego.
