### ISSUE TITLE
Prevenir que el launcher pueda ser cerrado por el usuario

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#39]
Prevenir que el launcher se pueda cerrar por el usuario por accidente (usado ALT + F4) por ejemplo, ya que seguramente deje un teclado conectado para jugar ciertos juegos. Si queres agregar chequeos adicionalesp para prevenir cagadas, adelante.

**Comment by Streq** [comment]
si es solo para prevenir alt+f4 la solución es `get_tree().set_auto_accept_quit(false)
`, si es para prevenir usuarios maliciosos o comandos mas complejos como Win+D que quieran ver si pueden entrar al sistema operativo, ahí es mucho más complicado y muy probablemente no pueda resolverse solo con gdscript

**Comment by PlayJamDevs** [comment]
> si es solo para prevenir alt+f4 la solución es `get_tree().set_auto_accept_quit(false) `, si es para prevenir usuarios maliciosos o comandos mas complejos como Win+D que quieran ver si pueden entrar al sistema operativo, ahí es mucho más complicado y muy probablemente no pueda resolverse solo con gdscript
> 
> EDIT: una solución que se me ocurre es deshabilitar ciertas teclas en el teclado con algún software tipo AutoHotkey, como F1...F12, Win, etc. Y autolaunchear en pantalla completa sin posibilidad de salir. Ahí creo que puede ir.

Dont guorry. Con el `set_auto_accept_quit` está más que bien.

**Comment by PlayJamDevs** [comment]
Despues si tengo tiempo, veo de hacer algo con el AutoHotkey. Por ahora que no puedan cerrarlo esta bien.
