### ISSUE TITLE
Crear Input Map

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/Play-Jam-Launcher-2#5]
[Original](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/wiki)

![Image](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/assets/111393321/0ee2045e-fde9-4ab7-95a3-da172f3b9fba)

Teclado:

* WASD: navegar menú
* ENTER: seleccionar
* ESC: volver

La aplicación del launcher **no debe poder cerrarse**, solamente forzándola con ALT + F4.

*Utilizar las acciones de ui por defecto de Godot o crear las acciones de ser necesario.*

**Comment by Streq** [comment]
Cómo se actúa en caso de que uno de los juegos no presente forma de salir usando joystick? sería prerequisito de admisión poder navegar y salir del juego con un joystick?

**Comment by Streq** [comment]
Pensando en esto había contemplado poder mappear alt+F4 al joystick de alguna manera como planteaste anteriormente, el tema es que

1. la secuencia de input _podría_ llegar a chocar con una combinación propia del juego
2. habría que hacer que el launcher desestime llamados de exit vía alt+F4 para que no se pueda salir usando esa misma secuencia

**Comment by PlayJamDevs** [comment]
> Pensando en esto había contemplado poder mappear alt+F4 al joystick de alguna manera como planteaste anteriormente, el tema es que
> 
> 1. la secuencia de input _podría_ llegar a chocar con una combinación propia del juego
> 2. habría que hacer que el launcher desestime llamados de exit vía alt+F4 para que no se pueda salir usando esa misma secuencia

1. Lo veo poco probable, pero puede ser. La combinación puede ser SELECT + START o START apretado 3 segundos. Es raro que algun juego use eso. 
2. Si, hay que prevenir que el launcher se cierre. Se me había ocurrido usar algo como [esto que menciono aca](https://github.com/PlayJamDevs/Play-Jam-Launcher-2/discussions/1) y mapear la combinación que comenté antes a ALT+F4. Hay que experimentar si es posible, usando ese software externo, ejecutarlo al abrir un juego y que se cierre al terminarlo. Si no es posible, con que el launcher no responda a ALT+F4 estaría bien.

> Cómo se actúa en caso de que uno de los juegos no presente forma de salir usando joystick? sería prerequisito de admisión poder navegar y salir del juego con un joystick?

No hay prequisitos (por ahora), más que el juego sea jugable. La idea es que cualquiera pueda meter sus juegos y despues se ordenarán bajo la categoría correspondiente.

Si durante el testeo de juegos random, vemos que es un problema que los juegos no tengan exit propio, ahí capaz podría evaluarse algunos requerimientos minimos.
